title:            Interferencias
description:      Grupo ciberactivista dedicado a organizar actividades y compartir
  información y opinión sobre derechos digitales, seguridad informática y temáticas
  similares.
reading_time:     true
words_per_minute: 200

# Your site's domain goes here (when testing locally leave blank or use http://localhost:4000)
url: http://localhost:4000

# Author information
author:
  name:           Interferencias
  avatar:         logo.png
  bio:            Grupo ciberactivista dedicado a organizar actividades y compartir
    información y opinión sobre derechos digitales, seguridad informática y temáticas
    similares.
  email:          interferencias@protonmail.com
  # Social networking links used in footer.
  telegram:       inter_ferencias
  twitter:        inter_ferencias
  mastodon:       interferencias
  github:         interferencias
  vimeo:          interferencias

# Background image to be tiled on all pages
background:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://jekyllrb.com/docs/permalinks/
permalink:   pretty

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - "_pages"
exclude:
  - ".git"
  - "node_modules"
  - ".gitignore"
  - ".jshintrc"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.js"
  - "LICENSE"
  - "package.json"
  - "README.md"
